port: "8000"

db:
    host: "localhost"       # Хост MongoDB (по умолчанию localhost)
    port: "27017"           # Порт MongoDB (по умолчанию 27017)
    username: "admin"       # Имя пользователя MongoDB (если используется аутентификация)
    dbname: "todo_db"       # Имя базы данных
    sslmode: "false"        # Режим SSL (true/false)